import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { draftMode } from "next/headers";
import DraftModeToolbar from "@/app/ui/DraftModeToolbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  const { isEnabled } = draftMode();
  return (
    <html lang="en">
      <body className={inter.className}>
        { isEnabled && <DraftModeToolbar/> }
        {children}
      </body>
    </html>
  );
}
